CREATE TABLE seccion (
id_seccion     INT(10) NOT NULL AUTO_INCREMENT,
nombre_seccion VARCHAR (50) NOT NULL,

CONSTRAINT PK_SECCION PRIMARY KEY (id_seccion)
)ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;